export const ActionsTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
   
    SET_LIKES:"SET_LIKES",
    INCRESS_LIKE:"INCRESS_LIKE",
    DECRESS_LIKE:"DECRESS_LIKE",

    SET_ALL_CART_DATA:"SET_ALL_CART_DATA",
    SET_CART:"SET_CART",
    INCRESS_CART:"INCRESS_CART",
    DECRESS_CART:"DECRESS_CART",

    CHANGE_MODE:"CHANGE_MODE",

    USER:"USER"
}